[package]
name = "guestbook"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "guestbook"
path = "src/main.rs"

[dependencies]
cgi = "0.8.0"
html-escape = "0.2.13"
rusqlite = "0.36.0"
url = "2.5.4"
