#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

SERVER="${1:-}"
if [[ "${SERVER}" == "" ]]; then
  echo "Usage: $0 <server>"
  echo "Available servers: apache, gohttpd"
  exit 1
fi

docker run \
  --rm \
  --interactive \
  --tty \
  --name "${SERVER}" \
  --memory 16G \
  --network host "webserver-${SERVER}:latest"

